EnglishNote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('note/', include("Note.urls")),
    path('', include('accounts.urls')),
]

Note/urls.py
from django.urls import path
from . import views

app_name = 'Note'

urlpatterns = [
    path('book/', views.IndexView.as_view(), name='index'),
    path('home/', views.BookView.as_view(), name='book'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('book/form/word/', views.AddPostView.as_view(), name='form_word'),
    path('book/form/<int:pk>', views.AddWordView.as_view(), name='form'),
    path('book/form/book/', views.BookCreateView.as_view(), name='book_create'),
    path('book/<int:pk>', views.PageView.as_view(), name='page'),
    path('upload/', views.uproad, name='upload'),
    path('note', views.noteView.as_view()),
    path('<int:pk>/update/', views.BookEditView.as_view(), name='editBook'),
    path('<int:pk>/delete/', views.BookDelete.as_view(), name='deleteBook'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('', views.Login.as_view(), name='login'),
  path('logout/', views.Logout.as_view(), name='logout'),
]

Note/models.py
from unicodedata import category
from django.db import models
from django.utils import timezone
# Create your models here.


class Book(models.Model):
    name = models.CharField('名前', max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.name

class Category(models.Model):
    # 問題カテゴリ
    name = models.CharField('カテゴリ名', max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        # テキストの値を返す
        return self.name


class Post(models.Model):
    # 問題本文と答え
    question = models.TextField('問題文')
    answer = models.TextField('答え')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    # on_delete=models.PROTECT だと子のデータを消さないと親のデータは消せない
    book = models.ForeignKey(
        Book, verbose_name='単語帳名', on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(
        Category, verbose_name='カテゴリ', on_delete=models.PROTECT, null=True)

    def __str__(self):
        # テキストの値を返す
        return self.question

accounts/models.py
from django.db import models

# Create your models here.

Note/forms.py
from .models import Book, Post
from django import forms

class WordForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs["class"] = "form-control"
    self.fields['book'].widget.attrs['readonly'] = 'readonly'

  class Meta:
    model = Post
    fields = ('book', 'question', 'answer', 'category',)
    labels =  {'book': '単語帳', 'question': '問題', 'answer': '答え', 'category': 'カテゴリー'}
  
class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('book', 'question', 'answer', 'category',)
    labels =  {'book': '単語帳', 'question': '問題', 'answer': '答え', 'category': 'カテゴリー'}

class BookForm(forms.ModelForm):
  class Meta:
    model = Book
    fields = ('name',)
    labels = {'name': '名前'}

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'
      field.widget.attrs['placeholder'] = field.label
      

Note/views.py
# from django.views.generic import TemplateView
from django.views import generic
from .models import Post, Category, Book
from django.shortcuts import render
from .forms import PostForm, BookForm, WordForm
from django.urls import reverse_lazy
import csv
from io import TextIOWrapper, StringIO


class IndexView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.order_by('-created_at')


class BookView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        return Book.objects.order_by('-created_at')


class CategoryView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        category_pk = self.kwargs['pk']
        queryset = Post.objects.order_by(
            '-created_at').filter(category__pk=category_pk)
        return queryset

class DetailView(generic.DetailView):
    model = Post


class PageView(generic.ListView):
    model = Post
    paginate_by = 10
    template_name = 'paper.html'

    def get_queryset(self):
        book_pk = self.kwargs['pk']
        queryset = Post.objects.order_by(
            '-created_at').filter(book__pk=book_pk)
        return queryset


class AddWordView(generic.CreateView):
    model = Post
    form_class = WordForm
    template_name = 'Note/form.html'
    success_url = reverse_lazy("Note:book")

    def get_initial(self):
        book_pk = self.kwargs['pk']
        initial = super().get_initial()
        initial["book"] = book_pk
        category = Category.objects.get(pk=1)
        initial["category"] = category
        return initial


class AddPostView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'Note/form.html'
    success_url = reverse_lazy("Note:book")

    def get_initial(self):
        initial = super().get_initial()
        category = Category.objects.get(pk=1)
        initial["category"] = category
        return initial



class BookCreateView(generic.CreateView):
    model = Book
    form_class = BookForm
    template_name = 'Note/book_form.html'
    success_url = reverse_lazy("Note:book")

class BookEditView(generic.UpdateView):
    template_name = 'Note/update.html'
    model = Book
    fields = ('name',)
    success_url = reverse_lazy('Note:book')

class BookDelete(generic.DeleteView):
    # template_name = 'Note/book_confirm_delete.html'
    model = Book
    success_url = reverse_lazy('Note:book')

def uproad(request):
    if 'csv' in request.FILES:
        # 書き込みモードで開いたファイルオブジェクトはio.TextIOWrapper
        form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
        csv_file = csv.reader(form_data)
        for line in csv_file:
            # postに確認したデータ,createdにデータがあったかどうかが入る
            post, created = Post.objects.get_or_create(question=line[0])
            post.question = line[0]
            post.answer = line[1]
            post.category = Category.objects.get(name=line[2])
            post.book = Book.objects.get(name=line[3])
            post.save()
        return render(request, 'Note/success.html')
    else:
        return render(request, 'Note/upload.html')

class noteView(generic.TemplateView):
    template_name = 'Note/note.html'

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm

class Login(LoginView):
  form_class = LoginForm
  template_name = 'accounts/login.html'

class Logout(LoginRequiredMixin, LogoutView):
  template_name = 'accounts/login.html'

Note/templates/Note/base.html
{% load static %}
<!doctype html>
<html lang="ja" xmlns:display="http://www.w3.org/1999/xhtml">

<head>
  <link rel="icon" type="image/png" href="{% static 'img/enote.ico' %}">
  <title>E-note</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  {% block head %}
  {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#dadada">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
        aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'Note:book' %}" style="color:#204969">
        <img src="{% static 'img/enote.ico' %}" alt="My image" width="30" height="28"
          class="d-inline-block align-text-top">
        E-note</a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'Note:book' %}" style="color: #204969;">Home</a>
          </li>
          <!-- <a class="nav-link" href="{% url 'Note:book_create' %}" style="color: #204969;">単語帳を作る</a>
            <a class="nav-link" href="{% url 'Note:form_word' %}" style="color:#204969;">単語を追加する</a>
            <a class="nav-link" href="{% url 'Note:upload' %}" style="color:#204969;">CSVで単語を追加する</a> -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="color: #204969;" id="navbarDropdownMenuLink" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">Category
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% for category in category_list %}
              <li><a class="dropdown-item" href="{% url 'Note:category' category.pk %}"
                  style="display: inline; color:#204969" ;>{{category}}
                </a></li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
          <li>
            <a class="nav-link">ユーザー名：{{ user.get_username }}</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts:logout' %}">
              <i class="fa fa-fw fa-sign-out"></i>ログアウト</a>
            </a>
          </li>
          {% endif %}
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>

Note/templates/Note/book_confirm_delete.html
{% extends 'Note/base.html' %}

{% block content %}
<h2 class="mt-5" style="border-bottom: 3px solid rgba(218,218,218,1); color:#204969;">削除</h2>

<div class="mb-4 mt-4 card">
  <div class="card-header" style="color:#204969">単語帳</div>
  <div class="card-body">
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ book.name }}
          <div class="form-group text-right">
              <button type="submit" class="mt-3 submit btn 
              btn-outline-secondary">削除</button>
          </div>
      </form>
  </div>
</div>
{% endblock %}

Note/templates/Note/book_form.html
{% extends 'Note/base.html' %}

{% block content %}
<h2 class="mt-5" style="border-bottom: 3px solid rgba(218,218,218,1); color:#204969;">入力</h2>
<div class="mb-4 mt-4 card">
    <div class="card-header" style="color:#204969">単語帳の登録</div>
    <div class="card-body">
        <form class="form-group" method="post">
            {% csrf_token %}
            {% for item in form %}
                <div class="form-group">
                    <label for="{{item.id_for_label}}">{{item.label}}</label>
                    <input type="{{item.field.widget.input_type}}" 
                    class="form-control"
                    {% if item.field.required %}required{% endif %}
                    name="{{item.name}}"
                    id="{{item.id_for_label}}">
                </div>
            {% endfor %}
            <button type="submit" class="mt-3 submit btn btn-outline-secondary">登録</button>
            <input type="hidden" name="next" value="{{ next }}"/>
        </form>
    </div>
</div>
{% endblock %}

Note/templates/Note/book_list.html
{% extends 'Note/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<h2 class="mt-5" style="border-bottom: 3px solid rgba(218,218,218,1); color:#204969;">一覧</h2>
<div class="row row-cols-1 row-cols-md-3 g-4 mt-4">
  <div class="col">
    <div class="card bg_test mb-4" onclick="frameClick();">
      <div class="card-header" style="color:#204969">単語帳を追加</div>
      <div class="card-body bg_test_aria">
      </div>
    </div>
  </div>
  {% for book in object_list %}
  <div class="col">
    <div class="card mb-4">
      <div class="card-header" style="color:#204969">単語帳</div>
      <div class="card-body">
        <h5 class="card-title mb-4" style="color:#204969">{{book.name}}</h5>
        <div class="btn-group-vertical">
          <a href="{% url 'Note:page' pk=book.pk %}" class="btn btn-outline-dark mb-2" style="color:#204969">単語を見る</a>
          <a href="#" class="btn btn-outline-dark dropdown-toggle" role="button" id="dropdownMenuLink"
            data-bs-toggle="dropdown" aria-expanded="false" style="color:#204969">編集</a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'Note:form' pk=book.pk %}" style="color:#204969">入力して単語を追加する</a></li>
            <li><a class="dropdown-item" href="{% url 'Note:upload' %}" style="color:#204969">CSVで単語を追加する</a></li>
            <li><a class="dropdown-item" href="{% url 'Note:editBook' pk=book.pk %}" style="color:#204969">名前変更</a></li>
            <li><a class="dropdown-item" href="{% url 'Note:deleteBook' pk=book.pk %}" style="color:#204969">削除</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<script type="text/javascript">
  function frameClick() {
    document.location.href = "{% url 'Note:book_create' %}";
  }
</script>
{% include 'Note/page.html' %}

{% endblock %}

Note/templates/Note/form.html
{% extends 'Note/base.html' %}

{% block content %}
<h2 class="mt-5" style="border-bottom: 3px solid rgba(218,218,218,1);color:#204969;">入力</h2>

<div class="mb-4 mt-4 card">
    <div class="card-header" style="color:#204969">単語の登録</div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <div class="form-group text-right">
                <button type="submit" class="mt-3 submit btn btn-outline-secondary">登録</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Note/templates/Note/note.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Blog - Tailsaw </title>
  <link rel="stylesheet" href="https//cdn.rawgit.com/jgthms/bulma/master/css/bulma.min.css">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="../css/bulma-divider.min.css">

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Nunito&display=swap');
  	body {font-family: 'Nunito', sans-serif;};
    nav.navbar {
      height: 6rem !important;
      box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06) !important;
    }
  </style>
</head>

<body>
  <!-- START NAV -->
  <nav class="navbar">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="../">
          <img src="../images/bulma.png" alt="Logo">
        </a>
        <span class="navbar-burger burger" data-target="navbarMenu">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </div>
      <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-end">
          <div class=" navbar-item">
            <div class="control has-icons-left">
              <input class="input is-rounded" type="email" placeholder="Search">
              <span class="icon is-left">
                <i class="fa fa-search"></i>
              </span>
            </div>
          </div>
          <a class="navbar-item is-active is-size-5 has-text-weight-semibold">
            Home
          </a>
          <a class="navbar-item is-size-5 has-text-weight-semibold">
            Examples
          </a>
          <a class="navbar-item is-size-5 has-text-weight-semibold">
            Features
          </a>
        </div>
      </div>
    </div>
  </nav>
  <!-- END NAV -->

  <!-- Image -->
  <section class="hero ">
    <div class="hero-body">
      <div class="container">
        <div class="columns">
          <div class="column is-8 is-offset-2">
            <figure class="image is-16by9">
              <img src="../images/first-post.png" alt="">
            </figure>
          </div>
        </div>

        <section class="section">
          <div class="columns">
            <div class="column is-8 is-offset-2">
              <div class="content is-medium">
                <h2 class="subtitle is-4">December 25, 2022</h2>
                <h1 class="title">Getting Started</h1>
                <p>This is a starter template for creating a beautiful, customizable blog with minimal
                  effort. You’ll only have to change a few settings and you’re ready to go. As with all Jigsaw sites,
                  configuration settings can be found in config</p>
              </div>
            </div>
          </div>
        </section>

        <div class="is-divider"></div>

        <section class="section">
          <div class="columns">
            <div class="column is-8 is-offset-2">
              <div class="content is-medium">
                <h2 class="subtitle is-4">December 25, 2022</h2>
                <h1 class="title">Getting Started</h1>
                <p>This is a starter template for creating a beautiful, customizable blog with minimal
                  effort. You’ll only have to change a few settings and you’re ready to go. As with all Jigsaw sites,
                  configuration settings can be found in config</p>
              </div>
            </div>
          </div>
        </section>


      </div>
    </div>
  </section>

  <!-- newsletter -->
  <section class="section">
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <div class="container has-text-centered is-fluid">
          <div class="hero is-light">
            <div class="hero-body">
              <h2 class="title is-4">Sign up for our newsletter</h2>
                <div class="column is-6 is-offset-3">
                  <div class="field has-addons has-addons-centered">
                    <div class="control is-expanded">
                      <input class="input " type="text" placeholder="Email address">
                    </div>
                    <div class="control">
                      <a class="button is-info">
                        Subscribe
                      </a>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Articles -->

  <section class="hero ">
    <div class="hero-body">
      <div class="container">

        <section class="section">
          <div class="columns is-variable is-8">
            <div class="column is-5 is-offset-1 ">
              <div class="content is-medium">
                <h2 class="subtitle is-5 has-text-grey">December 23, 2022</h2>
                <h1 class="title has-text-black is-3">Custom 404 Pages</h1>
                <p class="has-text-dark">This starter template includes a custom 404 Not Found error page, located at
                  /source/404.blade.php.
                  To preview the 404 page, you can visit /404 in your browser. Depending...</p>
              </div>
            </div>
            <div class="column is-5">
              <div class="content is-medium">
                <h2 class="subtitle is-5 has-text-grey">December 25, 2022</h2>
                <h1 class="title has-text-black is-3">Fuse Search</h1>
                <p class="has-text-dark">To provide fast, local search of your blog, this starter template comes with a
                  pre-built Vue.js
                  component that uses Fuse.js. Fuse.js is a "lightweight fuzzy-search library with no...</p>
              </div>
            </div>
          </div>
        </section>

        <div class="is-divider"></div>

        <section class="section">
          <div class="columns is-variable is-8">
            <div class="column is-5 is-offset-1">
              <div class="content is-medium">
                <h2 class="subtitle is-5 has-text-grey">December 25, 2022</h2>
                <h1 class="title has-text-black is-3">Getting Started</h1>
                <p class="has-text-dark">This is a starter template for creating a beautiful, customizable blog with
                  minimal
                  effort. You’ll only have to change a few settings and you’re ready to go. As with all Jigsaw sites,
                  configuration settings can be found in config</p>
              </div>
            </div>
            <div class="column is-5">
              <div class="content is-medium">
                <h2 class="subtitle is-5 has-text-grey">December 25, 2022</h2>
                <h1 class="title has-text-black is-3">Getting Started</h1>
                <p class="has-text-dark">This is a starter template for creating a beautiful, customizable blog with
                  minimal
                  effort. You’ll only have to change a few settings and you’re ready to go. As with all Jigsaw sites,
                  configuration settings can be found in config</p>
              </div>
            </div>
          </div>
        </section>


      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Bulma - Blog theme</strong> by <a href="https://gonzalojs.com">Gonzalo Gutierrez</a>. Based on the <a
          href="http://jigsaw-blog-staging.tighten.co/">jigsaw-blog</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>
      </p>
    </div>
  </footer>

  <script>
    document.addEventListener('DOMContentLoaded', () => {

      // Get all "navbar-burger" elements
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

      // Check if there are any navbar burgers
      if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach(el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });
      }

    });
  </script>

</body>

</html>

Note/templates/Note/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">

    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    {% for link_page in page_obj.paginator.page_range %}
    {% if link_page == page_obj.number %}
    <li class="page-item active">
      <a class="page-link" href="?{% url_replace request 'page' link_page %}">
        {{ link_page }}
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?{% url_replace request 'page' link_page %}">
        {{ link_page }}
      </a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

Note/templates/Note/paper.html
{% extends 'Note/base.html' %}

{% block content %}
<table>
  <caption>{{book_pk}}</caption>
  <thead>
    <tr>
      <th>問題</th>
      <th>答え</th>
      <th>カテゴリー</th>
      <th>音声</th>
    </tr>
  <tbody>
    {% for post in post_list %}
    <tr>
      <th>{{post.question}}</th>
      <th>{{post.answer}}</th>
      <th>{{post.category}}</th>
      <th></th>
    </tr>
    {% endfor %}

  </tbody>
  </thead>

</table>
{% endfor %}

{% include 'Note/page.html' %}

{% endblock %}

Note/templates/Note/post_detail.html
{% extends 'Note/base.html' %}

{% block content %}
<div class="card mb-3 mt-4">
  <h4 class="card-header bg-dark text-white">{{ post.question }}</h4>
  <div class="card-body">
    <h3>{{ post.answer | linebreaksbr | urlize}}</h3>
    <br /><br />
    <a href="{{request.META.HTTP_REFERER}}" class="btn btn-dark">問題に戻る</a>
  </div>
</div>

{% endblock %}

Note/templates/Note/post_list.html
{% extends 'Note/base.html' %}

{% block content %}
<h2 class="mt-5" style="border-bottom: 3px solid rgba(218,218,218,1); color:#204969;">一覧</h2>

<table class="table table-hover md-4 mt-4">
  <caption>{{book_pk}}</caption>
  <thead class="sticky-top">
    <tr>
      <th>問題</th>
      <th>答え</th>
      <th>カテゴリー</th>
      <th>音声</th>
    </tr>
  <tbody>
    {% for post in post_list %}
    <tr>
      <th>{{post.question}}</th>
      <th>{{post.answer}}</th>
      <th>{{post.category}}</th>
      <th><button id="button" class="btn btn-outline-secondary" onclick="pronounce('{{post.question}}')">再生</button></th>
    </tr>
    {% endfor %}

  </tbody>
  </thead>

</table>

{% include 'Note/page.html' %}
<script type="text/javascript">
  'use strict'

  function pronounce(word){
    let u = new SpeechSynthesisUtterance();
    u.lang = 'en-US';
    u.text = word;
    speechSynthesis.speak(u);
  }
</script>
{% endblock %}

Note/templates/Note/success.html
{% extends 'Note/base.html' %}

{% block content %}
<div class="jumbotron">
  <h2 class="mt-5" style="border-bottom: 3px solid rgba(218,218,218,1); color:#204969;">登録完了</h2>
  <p class="lead mt-4">
    <a class="btn btn-outline-secondary" href="{% url 'Note:book' %}" role="button">戻る</a>
  </p>
</div>
{% endblock %}

Note/templates/Note/upload.html
{% extends 'Note/base.html' %}
{% load static %}

{% block content %}
<h2 class="mt-5 mb-5" style="border-bottom: 3px solid rgba(218,218,218,1); color:#204969;">ファイル選択</h2>

<div class="container mt-4">
  <form action="{% url 'Note:upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="drop-zone" style="border: 3px dotted; padding: 30px;   border-color: rgba(218,218,218,1);
    ">
      <label for="formfile" class="form-label">ファイルをドラッグ＆ドロップもしくは</label>
      <input class="form-control" type="file" name="csv" id="formFileMultiple" multiple>
    </div>
    <button type="submit" class="mt-3 submit btn btn-outline-secondary">登録</button>
  </form>
</div>

{% endblock %}